update pika
to make projects that depend on this repo compatible with newer pythons:
```
  File "/home/vdloo/.virtualenvs/hypernode-api/lib/python3.7/site-packages/eventsender/__init__.py", line 5, in <module>
    import pika
  File "/home/vdloo/.virtualenvs/hypernode-api/lib/python3.7/site-packages/pika/__init__.py", line 22, in <module>
    from pika.adapters import BaseConnection
  File "/home/vdloo/.virtualenvs/hypernode-api/lib/python3.7/site-packages/pika/adapters/__init__.py", line 39, in <module>
    from pika.adapters.libev_connection import LibevConnection
  File "/home/vdloo/.virtualenvs/hypernode-api/lib/python3.7/site-packages/pika/adapters/libev_connection.py", line 103
    self.async = None
             ^
SyntaxError: invalid syntax
```

- fix broken improperly configured tests
- add python3.7 to tox so those tests will also run if that version is available on the system
- update pika from 0.10.0 to 0.13.1